  name : Deploy to ECS
  on : 
    push :
      branches : main
  jobs :
    build : 
      name: CI
      runs-on: ubuntu-latest
      outputs:
       ecrImage: ${{ steps.build-image.outputs.ecrImage }}
      steps:
      - name: Check out latest code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: next-image
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:latest
          echo "ecrImage=$REGISTRY/$REPOSITORY:latest" >> "$GITHUB_OUTPUT"
          echo $ecrImage
          echo "$ecrImage"

    deploy:
      name: CD
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Check out latest code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_DEFINITION_NAME }} \
          --query taskDefinition > task-definition.json
      
      - name: updating task definition
        env:
          ecrImage: ${{ needs.build.outputs.ecrImage }}
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn: task-definition.json
          container-name: next-container
          image: 875986302224.dkr.ecr.eu-north-1.amazonaws.com/next-image:latest
        
      
      - name: Deploy Amazon ECS task definition
        env: 
          ECS_SERVICE: next-service
          ECS_CLUSTER: next-cluster
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false